import os, datetime
desktop = os.path.join(os.path.join(os.path.expanduser('~')),'Desktop')
os.chdir(desktop)
_dateTime = str(datetime.datetime.now())
file = open("index.html","w")
file.write('<!DOCTYPE html>')
file.write('<html>')
file.write('<head>')
file.write('<style>')
file.write('img {')
file.write('display: block;')
file.write('margin-left: auto;')
file.write('margin-right: auto;')
file.write('}')
file.write('h2 {')
file.write('width: 100%;')
file.write('text-align:center;')
file.write('}')
file.write('</style>')
file.write('</head>')
file.write('<body>')
file.write('<img src="picFile.jpg" alt="cam" style="width:50%;">')
file.write('<h2>')
file.write(_dateTime)
file.write('</h2>')
file.write('</body>')
file.write('</html>')
file.close()